# Generated by Django 4.2.11 on 2024-07-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alkitaab', '0004_ibadatitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibadat',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
